version: '3.0'
services:
  resource-service-database:
    container_name: resource-service-database
    image: gvenzl/oracle-xe:latest
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: "oracle"
      ORACLE_DATABASE: "resource_service"
    networks:
      backend:
        aliases:
          - "resource-service-database"

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      backend:
        aliases:
          - "rabbitmq"

networks:
  backend:
    driver: bridge