global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'storage-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['storage-service:8084']